### ISSUE TITLE
`install-command` command is only used for installing the PR but not base revision

### ISSUE THREAD

**Issue by smheidrich** [Bibo-Joshi/pyright-type-completeness#4]
Is there any reason why the [base installation proceeds via a hardcoded `pip install . -U`](https://github.com/Bibo-Joshi/pyright-type-completeness/blob/fc72c143df047995a8e54991a6b269528df41cf3/action.yml#L61) instead of via the [`install-command` input](https://github.com/Bibo-Joshi/pyright-type-completeness/blob/fc72c143df047995a8e54991a6b269528df41cf3/action.yml#L53) like the PR revision installation?

**Comment by smheidrich** [comment]
I actually no longer need this now that I found a different way to fix the issue I mention at the end of #5 - still curious if there is a reason why the commands should differ, though.

**Comment by Bibo-Joshi** [comment]
Thanks for reaching out! Nice to see that this is actually used by someone other than me :D 
No, there's no reason, I guess I just missed it. thanks for pointing it out and even sending a PR!
